name: Release GHCR

on:
  release:
    types: [published]
  workflow_dispatch:

# simplest example of using the rust-base action
jobs:
  ghcr-release:
    uses: init4tech/actions/.github/workflows/ghcr.yml@main
    permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write
