name: Docker ECR Push - Pecorino

on:
  push:
    branches: [main]
    tags:
      - v**
  workflow_dispatch:

permissions:
  packages: write
  contents: read
  id-token: write

# simplest example of using the rust-base action
jobs:
  docker-ecr-push:
    uses: init4tech/actions/.github/workflows/ecr-build-and-push.yml@main
    with:
      rust-binary-name: pecorino-signet
      environment: dev
      dockerfile-path: Dockerfile.pecorino
    secrets:
      aws-ecr-repository: ${{ secrets.AWS_ECR_REPOSITORY }}
      aws-ecr-deployer-role-arn: ${{ secrets.AWS_ECR_DEPLOYER_ROLE_ARN }}
